apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: {{NAMESPACE}}
  labels:
    app: helloworld
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: {{PORT}}
  selector:
    app: helloworld
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: {{NAMESPACE}}
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - name: helloworld
        ports:
        - containerPort: 80
        image: {{PULL_IMAGE}}
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
      imagePullSecrets:
      - name: {{PULL_SECRET}}
